[package]
name = "spectre-config"
description = "Configuration model, performance profiles and key bindings for Spectre"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
spectre-theme = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
xdg = { workspace = true }
