[package]
name = "spectre-lock"
description = "The Spectre lock screen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "spectre-lock"
path = "src/main.rs"

[dependencies]
spectre-config = { workspace = true }
spectre-draw = { workspace = true }
spectre-text = { workspace = true }
spectre-theme = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
pam = { version = "0.8", default-features = false, features = ["client"] }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }

[dependencies.smithay-client-toolkit]
version = "0.21"
default-features = false
features = ["calloop", "xkbcommon"]
